config/routes.rb
Rails.application.routes.draw do
  get 'guests/index'

  resources :vehicles

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'guests#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :vehicle
  validates_formatting_of :direct_upload_url, using: :url
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:vin, :mileage, :year, :make, :model, :transmission, :cylinders, :drivetrain, :body_type, :fuel_type, :body_style, :title_in, :mileage_is, :new_used, :exterior_color, :interior_color, :trim, :doors, :inventory_source, :engine, :highway_mpg, :wheels, :condition, :tag_number, :photos_taken, :active, :options, :city_mpg, :nada_wholesale, :nada_retail, :sale_status, :est_recond_cost, :age, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/guests/index.html.erb
<h1>Guests#index</h1>
<p>Find me in app/views/guests/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ModernClassics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/vehicles/_form.html.erb
<%= form_for @vehicle, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :vin, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :vin, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mileage, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :mileage, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :year, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :make, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :make, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :model, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :model, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :transmission, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :transmission, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cylinders, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :cylinders, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :drivetrain, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :drivetrain, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body_type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :body_type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fuel_type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fuel_type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body_style, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :body_style, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title_in, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :title_in, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mileage_is, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :mileage_is, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :new_used, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :new_used, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :exterior_color, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :exterior_color, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :interior_color, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :interior_color, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :trim, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :trim, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :doors, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :doors, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :inventory_source, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :inventory_source, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :engine, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :engine, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :highway_mpg, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :highway_mpg, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :wheels, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :wheels, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :condition, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :condition, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tag_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :tag_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :photos_taken, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :photos_taken, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :active, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :active, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :options, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :options, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city_mpg, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :city_mpg, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nada_wholesale, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nada_wholesale, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nada_retail, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nada_retail, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sale_status, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :sale_status, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :est_recond_cost, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :est_recond_cost, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :age, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comments, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :comments, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  vehicles_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Vehicle %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicles/index.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => Vehicle %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:vin) %></th>
      <th><%= model_class.human_attribute_name(:mileage) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:make) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:transmission) %></th>
      <th><%= model_class.human_attribute_name(:cylinders) %></th>
      <th><%= model_class.human_attribute_name(:drivetrain) %></th>
      <th><%= model_class.human_attribute_name(:body_type) %></th>
      <th><%= model_class.human_attribute_name(:fuel_type) %></th>
      <th><%= model_class.human_attribute_name(:body_style) %></th>
      <th><%= model_class.human_attribute_name(:title_in) %></th>
      <th><%= model_class.human_attribute_name(:mileage_is) %></th>
      <th><%= model_class.human_attribute_name(:new_used) %></th>
      <th><%= model_class.human_attribute_name(:exterior_color) %></th>
      <th><%= model_class.human_attribute_name(:interior_color) %></th>
      <th><%= model_class.human_attribute_name(:trim) %></th>
      <th><%= model_class.human_attribute_name(:doors) %></th>
      <th><%= model_class.human_attribute_name(:inventory_source) %></th>
      <th><%= model_class.human_attribute_name(:engine) %></th>
      <th><%= model_class.human_attribute_name(:highway_mpg) %></th>
      <th><%= model_class.human_attribute_name(:wheels) %></th>
      <th><%= model_class.human_attribute_name(:condition) %></th>
      <th><%= model_class.human_attribute_name(:tag_number) %></th>
      <th><%= model_class.human_attribute_name(:photos_taken) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:options) %></th>
      <th><%= model_class.human_attribute_name(:city_mpg) %></th>
      <th><%= model_class.human_attribute_name(:nada_wholesale) %></th>
      <th><%= model_class.human_attribute_name(:nada_retail) %></th>
      <th><%= model_class.human_attribute_name(:sale_status) %></th>
      <th><%= model_class.human_attribute_name(:est_recond_cost) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:comments) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.id %></td>
        <td><%= vehicle.vin %></td>
        <td><%= vehicle.mileage %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.transmission %></td>
        <td><%= vehicle.cylinders %></td>
        <td><%= vehicle.drivetrain %></td>
        <td><%= vehicle.body_type %></td>
        <td><%= vehicle.fuel_type %></td>
        <td><%= vehicle.body_style %></td>
        <td><%= vehicle.title_in %></td>
        <td><%= vehicle.mileage_is %></td>
        <td><%= vehicle.new_used %></td>
        <td><%= vehicle.exterior_color %></td>
        <td><%= vehicle.interior_color %></td>
        <td><%= vehicle.trim %></td>
        <td><%= vehicle.doors %></td>
        <td><%= vehicle.inventory_source %></td>
        <td><%= vehicle.engine %></td>
        <td><%= vehicle.highway_mpg %></td>
        <td><%= vehicle.wheels %></td>
        <td><%= vehicle.condition %></td>
        <td><%= vehicle.tag_number %></td>
        <td><%= vehicle.photos_taken %></td>
        <td><%= vehicle.active %></td>
        <td><%= vehicle.options %></td>
        <td><%= vehicle.city_mpg %></td>
        <td><%= vehicle.nada_wholesale %></td>
        <td><%= vehicle.nada_retail %></td>
        <td><%= vehicle.sale_status %></td>
        <td><%= vehicle.est_recond_cost %></td>
        <td><%= vehicle.age %></td>
        <td><%= vehicle.comments %></td>
        <td><%=l vehicle.created_at, format: :long %></td>
        <td>
          <%= link_to vehicle_path(vehicle), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to vehicle_path(vehicle), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vehicle_path,
            :class => 'btn btn-primary' %>

app/views/vehicles/new.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Vehicle %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicles/show.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => Vehicle %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:vin) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.vin %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mileage) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.mileage %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:year) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.year %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:make) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.make %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:model) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.model %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:transmission) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.transmission %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cylinders) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.cylinders %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:drivetrain) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.drivetrain %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:body_type) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.body_type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fuel_type) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.fuel_type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:body_style) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.body_style %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title_in) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.title_in %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mileage_is) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.mileage_is %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:new_used) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.new_used %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:exterior_color) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.exterior_color %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:interior_color) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.interior_color %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:trim) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.trim %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:doors) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.doors %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:inventory_source) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.inventory_source %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:engine) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.engine %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:highway_mpg) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.highway_mpg %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:wheels) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.wheels %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:condition) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.condition %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tag_number) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.tag_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:photos_taken) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.photos_taken %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:active) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.active %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:options) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.options %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:city_mpg) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.city_mpg %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nada_wholesale) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.nada_wholesale %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nada_retail) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.nada_retail %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sale_status) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.sale_status %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:est_recond_cost) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.est_recond_cost %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:age) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.age %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:comments) %></dt>
      <dd><pre class="prettyprint"><%= @vehicle.comments %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vehicles_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vehicle_path(@vehicle), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vehicle_path(@vehicle),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>